#!/usr/bin/env bash
# This script transfers a file from a client to a server using SCP

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign the arguments to variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Transfer the file using SCP to the user's home directory on the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/
