#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP header

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add custom header configuration
sudo sed -i '/http {/a \\tserver_tokens off;\n\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf

# Restart Nginx
sudo service nginx restart
