#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP header

# Add custom header configuration
sudo sed -i '/server_name _;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
