#!/usr/bin/env bash
# This script installs and configures HAproxy on lb-01

# Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Add backend server configuration
echo "
backend servers
    balance roundrobin
    server web-01 18.207.3.79:80 check
    server web-02 34.232.76.94:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# Restart HAproxy
sudo service haproxy restart
