#!/usr/bin/env bash
# This script provides information about MAC and IP addresses.

# Answer 1: The unique identifier of a network interface
# Answer 2: Is to devices connected to a network what postal address is to houses
