#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with a sleep 2 between each iteration.
# It prints "I am invincible!!!" when receiving a SIGTERM signal.

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
