#!/usr/bin/env bash
# This script gives information about the school file

file_path="school"

# Check if the file exists
if [ -e "school" ] then
    echo "school file exists"

    # Check if the file is empty
    if [ -s "school" ] then
        echo "school is not empty"

        # Check if the file is a regular file
        if [ -f "school" ] then
            echo "school is a regular file"
        fi
else
    echo "school file does not exist"
fi
