#!/usr/bin/env bash
# This script configures an Ubuntu server to change the IP address of localhost and facebook.com.

# Change localhost IP
sudo echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null

# Change facebook.com IP
sudo echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
